language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 1.4
script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.activate("."); Pkg.build(); Pkg.test("CircoCore"; coverage=false)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.3
      script: julia --project -e '
          include("docs/make.jl");'
      after_success: skip
